format_version: 2
common:
  tasks:
    deploy: &deploy
      script: |
        set -e

        helm upgrade --install --wait --timeout 300 \
          --namespace ${PROJECT}-$K8S_NAMESPACE \
          ${CHART_NAME}-$K8S_NAMESPACE \
          ./chart/${CHART_NAME}-*.tgz \
          --values ./chart/${K8S_NAMESPACE}.yml \
          --set postgresql.postgresqlPassword="${DATABASE_PASSWORD}" \
          --set config.secrets.DATABASE_PASSWORD="${DATABASE_PASSWORD}" \
          --set config.secrets.OAUTH_CLIENT_SECRET="${OAUTH_CLIENT_SECRET}" \
          --set config.secrets.AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY}"

    migrate: &migrate
      script: |
        set -e

        docker pull \
          ${REGISTRY}/${IMAGE}:${GO_PIPELINE_LABEL}

        echo -- done pulling

        docker run \
          -e DATABASE_HOST=${DATABASE_HOST} \
          -e DATABASE_NAME=${DATABASE_NAME} \
          -e DATABASE_USERNAME=${DATABASE_USERNAME} \
          -e DATABASE_PASSWORD=${DATABASE_PASSWORD} \
          -e ENVIRONMENT_NAME=${K8S_NAMESPACE} \
          -e DEBUG="knex:query" \
          ${REGISTRY}/${IMAGE}:${GO_PIPELINE_LABEL} \
          yarn knex \
          --knexfile ./src/database/knexfile.js \
          migrate:latest

    restore: &restore
      script: |
        set -ex

        function finish {
          echo "in GOCD. Kill all containers"
          ## Change ownership so that GoCD can clean up after itself
          docker run -v `pwd`:/tmp/mount alpine chown -R $(id -u):$(id -g) /tmp/mount
          ./auto/clean-up || true
        }

        trap finish EXIT

        ## ./prod-backup/backup/backup.sql
        ## psql -U username -h localhost -d postgres -c "DROP DATABASE \"$DATABASE\";"
        docker run \
        -e PGPASSWORD="$DATABASE_PASSWORD" \
        -v `pwd`/prod-backup:/mnt/ \
        -w /mnt/backup/ \
         postgres:11 psql --host=$DATABASE_HOST --dbname=$DATABASE_NAME --username=$DATABASE_USERNAME -c "DROP TABLE IF EXISTS \"codes\"; DROP TABLE IF EXISTS \"scans\"; DROP TABLE IF EXISTS \"knex_migrations\"; DROP TABLE IF EXISTS \"knex_migrations_lock\""

        docker run \
        -e PGPASSWORD="$DATABASE_PASSWORD" \
        -v `pwd`/prod-backup:/mnt/ \
        -w /mnt/backup/ \
         postgres:11 psql --host=$DATABASE_HOST --dbname=$DATABASE_NAME --username=$DATABASE_USERNAME -f /mnt/backup/backup.sql

    seed: &seed
      script: |
        set -e

        docker pull \
          ${REGISTRY}/${IMAGE}:${GO_PIPELINE_LABEL}

        echo -- done pulling

        docker run \
          -e DATABASE_HOST=${DATABASE_HOST} \
          -e DATABASE_NAME=${DATABASE_NAME} \
          -e DATABASE_USERNAME=${DATABASE_USERNAME} \
          -e DATABASE_PASSWORD=${DATABASE_PASSWORD} \
          -e ENVIRONMENT_NAME=${K8S_NAMESPACE} \
          -e DEBUG="knex:query" \
          ${REGISTRY}/${IMAGE}:${GO_PIPELINE_LABEL} \
          yarn knex \
          --knexfile ./src/database/knexfile.js \
          seed:run

    backup: &backup
      script: |

        function finish {
          echo "in GOCD. Kill all containers"
          ## Change ownership so that GoCD can clean up after itself
          docker run -v `pwd`:/tmp/mount alpine chown -R $(id -u):$(id -g) /tmp/mount
          ./auto/clean-up || true
        }


        trap finish EXIT

        set -e

        docker run \
        -e PGPASSWORD="$DATABASE_PASSWORD" \
        -v `pwd`/backup:/mnt/backup/ \
        -w /mnt/backup/ \
         postgres:11 pg_dump --no-owner --no-acl --host=$DATABASE_HOST --username=$DATABASE_USERNAME --dbname=$DATABASE_NAME -f /mnt/backup/backup.sql

         ls -lh backup/


pipelines:
  snacker-tracker-reporter-test:
    group: snacker-tracker-reporter
    label_template: "${git[:8]}"
    lock_behavior: unlockWhenFinished
    timer:
      spec: "* * * * * ? */15"
      only_on_changes: yes
    materials:
      git:
        type: configrepo
    environment_variables:
      # REGISTRY: VALUE PASSED DOWN FROM THE AGENT ITSELF
      IMAGE: snacker-tracker/reporter
      CHART_NAME: snacker-tracker-reporter
      PROJECT: snacker-tracker
    stages:
      - tests:
          jobs:
            tests:
              tasks:
                - script: |
                    ./auto/clean-up

                    function finish {
                      echo "in GOCD. Kill all containers"
                      ## Change ownership so that GoCD can clean up after itself
                      docker run -v `pwd`:/tmp/mount alpine chown -R $(id -u):$(id -g) /tmp/mount
                      ./auto/clean-up || true
                    }

                    trap finish EXIT


                    set -e

                    ./auto/test

                    set +e

              artifacts:
                - test:
                    source: coverage/

            lint:
              tasks:
                - script: |
                    set -e

                    ./auto/lint
                    ./auto/clean-up

            audit:
              tasks:
                - script: |
                    ##AUDIT_RESULT="$(./auto/yarn audit)"
                    AUDIT_RESULT="$(docker run -v `pwd`:/app/ -w /app/ node:10 yarn audit)"
                    set -e

                    echo "$AUDIT_RESULT"

                    if [ "$(echo $AUDIT_RESULT | grep High | wc -l)" -gt 0 ]; then
                      exit 1
                    fi

            validate-swagger:
              tasks:
                - script: |
                    set -e

                    ./auto/validate-swagger

  snacker-tracker-reporter-build:
    group: snacker-tracker-reporter
    label_template: "0.1.${COUNT}-${upstream}"
    lock_behavior: unlockWhenFinished
    materials:
      upstream:
        pipeline: snacker-tracker-reporter-test
        stage: tests
      git:
        type: configrepo
    environment_variables:
      # REGISTRY: VALUE PASSED DOWN FROM THE AGENT ITSELF
      IMAGE: snacker-tracker/reporter
      CHART_NAME: snacker-tracker-reporter
      PROJECT: snacker-tracker
    stages:
      - package:
          jobs:
            build-image:
              tasks:
                - script: |
                    set -e

                    cat package.json | jq ".version=\"$GO_PIPELINE_LABEL\"" > package-2.json
                    docker build --pull -t ${REGISTRY}/${IMAGE}:${GO_PIPELINE_LABEL} \
                      --label version=${GO_PIPELINE_LABEL} \
                      --label git-commit=${GO_REVISION_GIT} \
                      --label go-pipeline=${GO_PIPELINE_NAME} \
                      --label go-pipeline-counter=${GO_PIPELINE_COUNTER} \
                      --label go-pipeline-stage=${GO_STAGE_NAME} \
                      --label go-pipeline-stage-counter=${GO_STAGE_COUNTER} \
                      --label go-pipeline-job=${GO_JOB_NAME} \
                      --build-arg APP_VERSION=${GO_PIPELINE_LABEL} \
                      .

                    docker tag ${REGISTRY}/${IMAGE}:${GO_PIPELINE_LABEL} ${REGISTRY}/${IMAGE}:latest
                    docker push ${REGISTRY}/${IMAGE}:${GO_PIPELINE_LABEL}
                    docker push ${REGISTRY}/${IMAGE}:latest

            package:
              tasks:
                - script: |
                    set -e

                    helm lint helm-charts/${CHART_NAME}

                    helm package --version "$(echo $GO_PIPELINE_LABEL | awk -F '-' '{print $1}')" --app-version $GO_PIPELINE_LABEL ./helm-charts/${CHART_NAME}
              artifacts:
                - build:
                    source: snacker-tracker-reporter-*.tgz
                    destination: ./chart/
                - build:
                    source: helm-charts/values/*
                    destination: ./chart/

  snacker-tracker-reporter-deploy-qa:
    group: snacker-tracker-reporter
    label_template: "${upstream}"
    lock_behavior: unlockWhenFinished
    materials:
      upstream:
        pipeline: snacker-tracker-reporter-build
        stage: package
    environment_variables:
      K8S_NAMESPACE: qa
      CHART_NAME: snacker-tracker-reporter
      PROJECT: snacker-tracker
    secure_variables:
      DATABASE_PASSWORD: "AES:18jhrqGd0n44Gyb4Enbxww==:caltQWdr90nZA2ePrxQOuA=="
      AWS_SECRET_ACCESS_KEY: "AES:sD7ZqSU5xDUGEz6lwCBCOQ==:ujFaho4OGe60fY7+2OfOjeY/u5m3E2aYmlgS24PSP2GDWBEBvSug6D9NA/i+7qGl"
      OAUTH_CLIENT_SECRET: "AES:2KEgFgvsaHh+AAVMqiiVmw==:D0/G7yDH8uLiSuP9EKYQE5wB2MqeSYdn+eVMS9LWx1E5frpbJ6sYYlpWB7YFzsa/tc03vf2LAGs+mRsYUL3XMeU4iZx78ZPBZ3iCLs9dJYM="
    stages:
      - deploy:
          jobs:
            helm-upgrade:
              tasks:
                - fetch:
                    pipeline: snacker-tracker-reporter-build
                    stage: package
                    job: package
                    source: chart/
                    destination: ./
                - *deploy

  snacker-tracker-reporter-deploy-qa-seed:
    group: snacker-tracker-reporter
    label_template: "${upstream}"
    lock_behavior: unlockWhenFinished
    materials:
      git:
        type: configrepo
      upstream:
        pipeline: snacker-tracker-reporter-deploy-qa
        stage: deploy
    environment_variables:
      # REGISTRY: VALUE PASSED DOWN FROM THE AGENT ITSELF
      IMAGE: snacker-tracker/reporter
      CHART_NAME: snacker-tracker-reporter
      DATABASE_HOST: "snacker-tracker-reporter-qa-postgresql.snacker-tracker-qa.svc.cluster.local"
      DATABASE_NAME: snacker-tracker-reporter-qa
      DATABASE_USERNAME: postgres
      K8S_NAMESPACE: qa
      PROJECT: snacker-tracker
      AWS_ACCESS_KEY_ID: "AKIAIOSFODNN7EXAMPLE"
    secure_variables:
      DATABASE_PASSWORD: "AES:18jhrqGd0n44Gyb4Enbxww==:caltQWdr90nZA2ePrxQOuA=="
      AWS_SECRET_ACCESS_KEY: "AES:sD7ZqSU5xDUGEz6lwCBCOQ==:ujFaho4OGe60fY7+2OfOjeY/u5m3E2aYmlgS24PSP2GDWBEBvSug6D9NA/i+7qGl"
    stages:
      - backup-prod-data:
          jobs:
            backup:
              environment_variables:
                DATABASE_HOST: "snacker-tracker-reporter-prod-postgresql.snacker-tracker-prod.svc.cluster.local"
                DATABASE_NAME: snacker-tracker-reporter-prod
                DATABASE_USERNAME: postgres
                K8S_NAMESPACE: prod
              secure_variables:
                DATABASE_PASSWORD: "AES:18jhrqGd0n44Gyb4Enbxww==:caltQWdr90nZA2ePrxQOuA=="
              tasks:
                - *backup
              artifacts:
                - build:
                    source: backup
                    destination: ./prod-backup/

      - restore-prod-data:
          jobs:
            restore:
              tasks:
                - fetch:
                    pipeline: snacker-tracker-reporter-deploy-qa-seed
                    stage: backup-prod-data
                    job: backup
                    source: prod-backup/
                    destination: ./
                - *restore

      - migrate:
          jobs:
            migrate:
              tasks:
                - *migrate

      - sync-pictures:
          jobs:
            sync:
              tasks:
                - script: |
                    set -e

                    aws --endpoint https://s3.aws.k8s.fscker.org s3 sync s3://snacker-tracker-prod/ s3://snacker-tracker-qa/


  snacker-tracker-reporter-deploy-prod:
    group: snacker-tracker-reporter
    label_template: "${upstream}"
    lock_behavior: unlockWhenFinished
    materials:
      upstream:
        pipeline: snacker-tracker-reporter-deploy-qa
        stage: deploy
    environment_variables:
      K8S_NAMESPACE: prod
      CHART_NAME: snacker-tracker-reporter
      PROJECT: snacker-tracker
    secure_variables:
      DATABASE_PASSWORD: "AES:18jhrqGd0n44Gyb4Enbxww==:caltQWdr90nZA2ePrxQOuA=="
      AWS_SECRET_ACCESS_KEY: "AES:sD7ZqSU5xDUGEz6lwCBCOQ==:ujFaho4OGe60fY7+2OfOjeY/u5m3E2aYmlgS24PSP2GDWBEBvSug6D9NA/i+7qGl"
      OAUTH_CLIENT_SECRET: "AES:hpy0VQN7CbWpqLHeYSp3gg==:NWJ8+UVYpQxFoe2knRxqdLMXHOMHmo8fELcvQTT+T0xqn6yHgI2b+3TCtSLRlN4QhO6NELivcBrjVxJL47evz8No2hFke7y4eBQJGTp9LiM="
    stages:
      - deploy:
          approval:
            type: manual
          jobs:
            helm-upgrade:
              tasks:
                - fetch:
                    pipeline: snacker-tracker-reporter-build/snacker-tracker-reporter-deploy-qa
                    stage: package
                    job: package
                    source: chart/
                    destination: ./
                - *deploy

  snacker-tracker-reporter-deploy-prod-seed:
    group: snacker-tracker-reporter
    label_template: "${upstream}"
    lock_behavior: unlockWhenFinished
    materials:
      git:
        type: configrepo
      upstream:
        pipeline: snacker-tracker-reporter-deploy-prod
        stage: deploy
    environment_variables:
      REGISTRY: "registry.k8s.fscker.org"
      IMAGE: snacker-tracker/reporter
      CHART_NAME: snacker-tracker-reporter
      DATABASE_HOST: "snacker-tracker-reporter-prod-postgresql.snacker-tracker-prod.svc.cluster.local"
      DATABASE_NAME: snacker-tracker-reporter-prod
      DATABASE_USERNAME: postgres
      K8S_NAMESPACE: prod
      PROJECT: snacker-tracker
    secure_variables:
      DATABASE_PASSWORD: "AES:18jhrqGd0n44Gyb4Enbxww==:caltQWdr90nZA2ePrxQOuA=="

    stages:
      - migrate:
          approval:
            type: manual
          jobs:
            migrate:
              tasks:
                - *migrate

      - seed:
          approval:
            type: manual
          jobs:
            seeding:
              tasks:
                - *seed
