# Default values for snacker-tracker-recorder.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: registry.k8s.fscker.org/snacker-tracker/reporter
  # tag: stable
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  internal_port: 5000

ingress:
  enabled: false
  annotations:
#    certmanager.k8s.io/acme-challenge-type: dns01
#    certmanager.k8s.io/acme-dns01-provider: route53
#    certmanager.k8s.io/cluster-issuer: lets-encrypt-prod
    cert-manager.io/cluster-issuer: lets-encrypy-prod
  hosts:
    - host: chart-example.local
      paths: []

  tls: []

resources:
  requests:
    cpu: 0.01
    memory: 128Mi

postgresql:
  enabled: true
  service:
    port: 5432

nodeSelector: {}

tolerations: []

affinity: {}

config:
  env:
    PORT: "5000"
