#!/usr/bin/env bash

PG_PORT="$(docker-compose port pg 5432 | awk -F ':' '{ print $2 }')"

export PG_PORT

psql --host=0.0.0.0 --port="$PG_PORT" snacker-tracker-reporter-default snacker-tracker-reporter
