#!/usr/bin/env bash

set -e

export REPORTER_BASE_URL="${1}"

TOKEN_RESPONSE=$(curl --request POST \
--url "https://${ISSUER_DOMAIN}/oauth/token" \
--header 'content-type: application/json' \
--data "{\"client_id\":\"${CLIENT_ID}\",\"client_secret\":\"${CLIENT_SECRET}\",\"audience\":\"snacker-tracker-reporter\",\"grant_type\":\"client_credentials\"}")

TOKEN="$(echo "${TOKEN_RESPONSE}" | jq -r .access_token)"

CREATE_SCAN_RESPONSE=$(curl --fail "${REPORTER_BASE_URL}/v1/scans/" \
    -H 'Content-Type: application/json' \
    -H "Authorization: Bearer ${TOKEN}" \
    -d '{"code":"123123123","location":"ci-server"}')

echo "$CREATE_SCAN_RESPONSE" | jq .

curl "${REPORTER_BASE_URL}/v1/scans" | jq .
